# Generated by Django 4.2 on 2026-06-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
